language: cpp
compiler: clang
dist: trusty

addons:
  apt:
    packages: libboost-all-dev libgmp-dev zlib1g-dev libjemalloc-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
