language: cpp
compiler: g++
dist: xenial

addons:
  apt:
    packages: libboost-graph-dev libboost-iostreams-dev libgmp-dev zlib1g-dev libjemalloc-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
