language: cpp
compiler: clang
dist: bionic

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux_2_24_x86_64
           PLAT=manylinux_2_24_x86_64

install:
  - docker pull $DOCKER_IMAGE

addons:
  apt:
    packages: libboost-graph-dev libboost-iostreams-dev libgmp-dev zlib1g-dev liblzma-dev libjemalloc-dev libopenmpi-dev openmpi-bin

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh  
  - ls wheelhouse/
