language: cpp
compiler: clang
dist: bionic

matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64 PLAT=manylinux2014_x86_64

install:
- docker pull $DOCKER_IMAGE

addons:
  apt:
    packages: libboost-graph-dev libboost-iostreams-dev libgmp-dev zlib1g-dev liblzma-dev
      libjemalloc-dev libopenmpi-dev openmpi-bin python3-setuptools python3-wheels twine

script:
- mkdir build
- cd build
- cmake ..
- make
- make test
- cd ..
- docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
- ls wheelhouse
- twine upload --repository testpypi wheelhouse/*
