matrix:
  include:
  - dist: bionic
    language: cpp
    compiler: clang
    addons:
      apt:
        packages: libboost-graph-dev libboost-iostreams-dev libgmp-dev zlib1g-dev liblzma-dev
          libjemalloc-dev libopenmpi-dev openmpi-bin
    script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
 
  - sudo: required
    python: 3.9
    services: docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64 PLAT=manylinux2014_x86_64
    install:
      - docker pull $DOCKER_IMAGE

    script:
    - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /io/travis/build-wheels.sh
    - pip3 install --user --upgrade pip
    - pip3 install --user twine
    - python3 -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*

