language: cpp
compiler: clang
dist: bionic

matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64 PLAT=manylinux2014_x86_64

install:
- docker pull $DOCKER_IMAGE

addons:
  apt:
    packages: libboost-graph-dev libboost-iostreams-dev libgmp-dev zlib1g-dev liblzma-dev
      libjemalloc-dev libopenmpi-dev openmpi-bin twine

script:
- COMMIT_MSG=$(git log --oneline --format=%B -n 1 HEAD | head -n 1)
- mkdir build
- cd build
- cmake ..
- make
- make test
- cd ..
- [[ $COMMIT_MSG =~ pytb2-deploy ]] && docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE /io/travis/build-wheels.sh
- [[ $COMMIT_MSG =~ pytb2-deploy ]] && twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*
