version: 1.0.{build}
platform: x64

environment:
  matrix:
    - PYTHON: "C:\\Python35"

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip3.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan install .
  - cmd: dir
  - cmd: cmake ../
  - cmd: cmake --build . --config Release

test_script:
  - cmd: cd bin
  - cmd: encryption_test.exe
